#ifndef ESP32_7IN_EPAPER_WEATHER_STATION_CONFIG_H
#define ESP32_7IN_EPAPER_WEATHER_STATION_CONFIG_H

#include <Arduino.h>

const uint8_t UPDATE_TIME = 60; // minutes

#endif // ESP32_7IN_EPAPER_WEATHER_STATION_CONFIG_H
